# Site settings
title: Bedfordians Rifle Club
email: contact@bedfordiansrc.org
description: Bedfordians Rifle Club
baseurl:

#url: "http://www.artbymarie.info"

#collections:
#  links:
#    output: true


# Build settings
markdown: kramdown

include: ['_collections', '_pages', '_projects']

sass:
  sass_dir: /_scss

collections:
  archive_files:
    output: false

gems:
  - jekyll-sitemap