# Site settings
title: Bedfordians Rifle Club
email: contact@bedfordiansrc.org
description: Bedfordians Rifle Club
baseurl:

#url: "http://www.artbymarie.info"

#collections:
#  links:
#    output: true


# Build settings
markdown: kramdown

sass:
  sass_dir: /_scss
